/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class TestSceneUI extends Laya.Scene {
		public scoreLbl:Laya.Label;
		public BtnLeft:Laya.Sprite;
		public BtnRight:Laya.Sprite;
		public PRoot:Laya.Sprite;
		public line:Laya.Sprite;
		public car:Laya.Sprite;
		public wheel1:Laya.Sprite;
		public wheel2:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}